{
  imports = [
    ./assets.nix
    ./fonts.nix
    ./hyprland.nix
    ./niri.nix
    ./waybar.nix
    ./kitty.nix
    ./gtk.nix
    ./rofi.nix
    ./dunst.nix
    ./hyprlock.nix
    ./wlogout.nix
    ./fastfetch.nix
    ./wallpaper.nix
    ./yazi.nix
    ./lazyvim.nix
    ./doom/doom.nix
    ./vesktop.nix
  ];
}
