{ ... }:

let
  palette = import ./palette.nix;
in
{
  programs.vesktop = {
    enable = true;

    vencord = {
      /*
       * The theme itself is generated by Home Manager and installed by the
       * native Vencord Home Manager module. No mutable theme files or
       * activation scripts are required.
       */
      themes."hyprmoni.theme.css" = ''
        /**
         * Hyprmoni for Vesktop
         *
         * Reuses the exact Hyprmoni palette from palette.nix.
         * The CSS intentionally removes Discord's rounded "modern" UI
         * treatment and replaces the remaining default grey surfaces.
         */

        :root,
        body,
        #app-mount {
          /* Hyprmoni */
          --hyprmoni-void: ${palette.void};
          --hyprmoni-panel: ${palette.panel};
          --hyprmoni-wine: ${palette.wine};
          --hyprmoni-wine-dark: ${palette.wineDark};
          --hyprmoni-pink: ${palette.pink};
          --hyprmoni-hot-pink: ${palette.hotPink};
          --hyprmoni-blush: ${palette.blush};
          --hyprmoni-peach: ${palette.peach};
          --hyprmoni-muted: ${palette.muted};
          --hyprmoni-green: ${palette.green};

          /* ----------------------------------------------------------------
           * Discord legacy variables
           * ---------------------------------------------------------------- */

          --background-primary: var(--hyprmoni-void) !important;
          --background-secondary: var(--hyprmoni-panel) !important;
          --background-secondary-alt: var(--hyprmoni-panel) !important;
          --background-tertiary: var(--hyprmoni-void) !important;
          --background-floating: var(--hyprmoni-panel) !important;

          --home-background: var(--hyprmoni-void) !important;
          --channeltextarea-background: var(--hyprmoni-panel) !important;
          --chat-background: var(--hyprmoni-void) !important;
          --chat-input-container-background: var(--hyprmoni-void) !important;
          --card-primary-bg: var(--hyprmoni-panel) !important;
          --card-secondary-bg: var(--hyprmoni-panel) !important;
          --card-primary-pressed-bg: var(--hyprmoni-wine-dark) !important;
          --card-secondary-pressed-bg: var(--hyprmoni-wine-dark) !important;

          --deprecated-card-bg: var(--hyprmoni-panel) !important;
          --deprecated-text-input-bg: var(--hyprmoni-void) !important;

          --button-secondary-background: var(--hyprmoni-panel) !important;
          --button-secondary-background-hover: var(--hyprmoni-wine-dark) !important;
          --button-secondary-background-active: var(--hyprmoni-wine) !important;
          --button-secondary-text: var(--hyprmoni-blush) !important;

          /* ----------------------------------------------------------------
           * Discord modern variables
           * ---------------------------------------------------------------- */

          --bg-base-primary: var(--hyprmoni-void) !important;
          --bg-base-secondary: var(--hyprmoni-panel) !important;
          --bg-base-tertiary: var(--hyprmoni-void) !important;

          --bg-surface-raised: var(--hyprmoni-panel) !important;
          --bg-surface-overlay: var(--hyprmoni-panel) !important;
          --bg-surface-underlay: var(--hyprmoni-void) !important;
          --bg-surface-high: var(--hyprmoni-panel) !important;
          --bg-surface-highest: var(--hyprmoni-panel) !important;
          --background-surface-high: var(--hyprmoni-panel) !important;
          --background-surface-highest: var(--hyprmoni-panel) !important;

          --bg-mod-faint: var(--hyprmoni-wine-dark) !important;
          --bg-mod-subtle: var(--hyprmoni-wine-dark) !important;
          --bg-mod-normal: var(--hyprmoni-wine) !important;
          --bg-mod-strong: var(--hyprmoni-wine) !important;

          --background-modifier-hover: color-mix(
            in srgb,
            var(--hyprmoni-pink) 10%,
            transparent
          ) !important;

          --background-modifier-active: color-mix(
            in srgb,
            var(--hyprmoni-pink) 18%,
            transparent
          ) !important;

          --background-modifier-selected: color-mix(
            in srgb,
            var(--hyprmoni-pink) 24%,
            transparent
          ) !important;

          --background-mentioned: color-mix(
            in srgb,
            var(--hyprmoni-pink) 14%,
            transparent
          ) !important;

          --background-mentioned-hover: color-mix(
            in srgb,
            var(--hyprmoni-pink) 21%,
            transparent
          ) !important;

          --background-message-hover: color-mix(
            in srgb,
            var(--hyprmoni-panel) 88%,
            var(--hyprmoni-pink)
          ) !important;

          --chat-border: var(--hyprmoni-wine) !important;
          --border-subtle: var(--hyprmoni-wine) !important;
          --border-normal: var(--hyprmoni-wine) !important;
          --border-strong: var(--hyprmoni-pink) !important;
          --input-border-default: var(--hyprmoni-wine) !important;
          --input-border-hover: var(--hyprmoni-pink) !important;

          --channel-icon: var(--hyprmoni-muted) !important;
          --channels-default: var(--hyprmoni-muted) !important;

          /* Controls */
          --control-secondary-background-default: var(--hyprmoni-panel) !important;
          --control-secondary-background-hover: var(--hyprmoni-wine-dark) !important;
          --control-secondary-background-active: var(--hyprmoni-wine) !important;
          --control-secondary-border-default: var(--hyprmoni-wine) !important;
          --control-secondary-border-hover: var(--hyprmoni-pink) !important;
          --control-secondary-text-default: var(--hyprmoni-blush) !important;
          --control-secondary-text-hover: var(--hyprmoni-hot-pink) !important;

          --control-primary-background-default: var(--hyprmoni-pink) !important;
          --control-primary-background-hover: var(--hyprmoni-hot-pink) !important;
          --control-primary-background-active: var(--hyprmoni-wine) !important;
          --control-primary-border-default: var(--hyprmoni-pink) !important;
          --control-primary-border-hover: var(--hyprmoni-hot-pink) !important;
          --control-primary-text-default: var(--hyprmoni-void) !important;
          --control-primary-text-hover: var(--hyprmoni-void) !important;

          --button-filled-brand-background: var(--hyprmoni-pink) !important;
          --button-filled-brand-background-hover: var(--hyprmoni-hot-pink) !important;
          --button-filled-brand-text: var(--hyprmoni-void) !important;

          /* Brand */
          --brand-500: var(--hyprmoni-pink) !important;
          --brand-560: var(--hyprmoni-hot-pink) !important;
          --brand-experiment: var(--hyprmoni-pink) !important;
          --control-brand-foreground: var(--hyprmoni-pink) !important;
          --control-brand-foreground-new: var(--hyprmoni-pink) !important;
          --focus-primary: var(--hyprmoni-hot-pink) !important;

          /* Text */
          --text-default: var(--hyprmoni-blush) !important;
          --text-muted: var(--hyprmoni-muted) !important;
          --text-subtle: var(--hyprmoni-muted) !important;
          --text-normal: var(--hyprmoni-blush) !important;
          --text-link: var(--hyprmoni-peach) !important;
          --header-primary: var(--hyprmoni-blush) !important;
          --header-secondary: var(--hyprmoni-muted) !important;
          --interactive-normal: var(--hyprmoni-blush) !important;
          --interactive-hover: var(--hyprmoni-hot-pink) !important;
          --interactive-active: var(--hyprmoni-pink) !important;
          --interactive-muted: var(--hyprmoni-muted) !important;

          /* Icons */
          --icon-primary: var(--hyprmoni-blush) !important;
          --icon-secondary: var(--hyprmoni-muted) !important;
          --icon-tertiary: var(--hyprmoni-muted) !important;
          --icon-muted: var(--hyprmoni-muted) !important;
          --icon-brand: var(--hyprmoni-pink) !important;

          /* ----------------------------------------------------------------
           * Kill the Discord "pill/card" aesthetic.
           *
           * Discord uses a collection of radius variables rather than a
           * single variable. Keeping avatar/ring variables untouched lets
           * avatars remain circular while UI surfaces become square.
           * ---------------------------------------------------------------- */

          --radius-xs: 0px !important;
          --radius-sm: 0px !important;
          --radius-md: 0px !important;
          --radius-lg: 0px !important;
          --radius-xl: 0px !important;

          --radius-xxs: 0px !important;
          --radius-xs: 0px !important;
          --radius-sm: 0px !important;
          --radius-md: 0px !important;
          --radius-lg: 0px !important;
          --radius-xl: 0px !important;

          /* Newer Discord control aliases */
          --radius-secondary: 0px !important;
          --radius-primary: 0px !important;
        }

        * {
          box-sizing: border-box;
        }

        body,
        #app-mount {
          background: var(--hyprmoni-void) !important;
          color: var(--hyprmoni-blush) !important;
          font-family: "Mali", "AdwaitaMono Nerd Font", sans-serif !important;
        }

        *,
        button,
        input,
        textarea {
          font-family: "Mali", "AdwaitaMono Nerd Font", sans-serif !important;
        }

        /* ==================================================================
         * CORE APP SURFACES
         * ================================================================== */

        [class*="appMount"],
        [class*="base_"],
        [class*="bg_"],
        [class*="app_"] {
          background: var(--hyprmoni-void) !important;
        }

        [class*="guilds"],
        [class*="guilds"] > div {
          background: var(--hyprmoni-void) !important;
        }

        [class*="sidebar"] {
          background: var(--hyprmoni-panel) !important;
          border-right: 1px solid var(--hyprmoni-wine) !important;
        }

        [class*="panels"] {
          background: var(--hyprmoni-panel) !important;
          border-radius: 0 !important;
          border-top: 1px solid var(--hyprmoni-wine) !important;
        }

        main[class*="chatContent"],
        [class*="chatContent"],
        [class*="chat"],
        [class*="contentRegion"],
        [class*="contentRegionScroller"],
        [class*="standardSidebarView"] {
          background: var(--hyprmoni-void) !important;
        }

        /* Top channel / page headers */
        header,
        [class*="title"],
        [class*="headerBar"],
        [class*="header_"] {
          background: var(--hyprmoni-panel) !important;
          border-bottom-color: var(--hyprmoni-wine) !important;
        }

        /* Member list */
        [class*="membersWrap"],
        [class*="members"] {
          background: var(--hyprmoni-panel) !important;
        }

        /* ==================================================================
         * FRIENDS / HOME PAGE
         * ================================================================== */

        [class*="peopleColumn"],
        [class*="nowPlayingColumn"],
        [class*="friendsTable"],
        [class*="peopleList"],
        [class*="tabBody"] {
          background: var(--hyprmoni-void) !important;
        }

        [class*="tabBar"],
        [class*="tabBar"] > * {
          background: var(--hyprmoni-panel) !important;
          border-radius: 0 !important;
        }

        [class*="tabBar"] [class*="item"],
        [role="tab"] {
          background: transparent !important;
          border-radius: 0 !important;
          color: var(--hyprmoni-muted) !important;
          box-shadow: none !important;
        }

        [class*="tabBar"] [class*="item"]:hover,
        [role="tab"]:hover {
          background: var(--hyprmoni-wine-dark) !important;
          color: var(--hyprmoni-blush) !important;
        }

        [class*="tabBar"] [class*="item"][class*="selected"],
        [role="tab"][aria-selected="true"] {
          background: var(--hyprmoni-wine) !important;
          color: var(--hyprmoni-blush) !important;
          border-bottom: 2px solid var(--hyprmoni-pink) !important;
        }

        /* Online / All / Pending button-like surfaces */
        [class*="friend"] button,
        [class*="friends"] button,
        [class*="people"] button {
          border-radius: 0 !important;
        }

        /* ==================================================================
         * SEARCH FIELDS
         * ================================================================== */

        [class*="searchBar"],
        [class*="searchBox"],
        [class*="searchPage"],
        [class*="searchResult"] {
          border-radius: 0 !important;
        }

        [class*="searchBar"] {
          background: var(--hyprmoni-void) !important;
          border: 1px solid var(--hyprmoni-wine) !important;
          box-shadow: none !important;
        }

        [class*="searchBar"]:focus-within {
          border-color: var(--hyprmoni-pink) !important;
          box-shadow: 0 0 0 1px var(--hyprmoni-pink) !important;
        }

        input,
        textarea,
        [role="textbox"] {
          background-color: var(--hyprmoni-void) !important;
          border-color: var(--hyprmoni-wine) !important;
          color: var(--hyprmoni-blush) !important;
          border-radius: 0 !important;
          box-shadow: none !important;
        }

        input:focus,
        textarea:focus,
        [role="textbox"]:focus {
          border-color: var(--hyprmoni-pink) !important;
          outline: none !important;
        }

        input::placeholder,
        textarea::placeholder {
          color: var(--hyprmoni-muted) !important;
        }

        /* ==================================================================
         * BUTTONS
         * ================================================================== */

        button,
        [role="button"] {
          border-radius: 0 !important;
        }

        button[class*="lookFilled"][class*="colorBrand"],
        button[class*="lookFilled"][class*="colorPrimary"],
        [class*="button"][class*="brand"] {
          background: var(--hyprmoni-pink) !important;
          border: 1px solid var(--hyprmoni-pink) !important;
          color: var(--hyprmoni-void) !important;
          border-radius: 0 !important;
          box-shadow: none !important;
        }

        button[class*="lookFilled"][class*="colorBrand"]:hover,
        button[class*="lookFilled"][class*="colorPrimary"]:hover,
        [class*="button"][class*="brand"]:hover {
          background: var(--hyprmoni-hot-pink) !important;
          border-color: var(--hyprmoni-hot-pink) !important;
        }

        button[class*="lookBlank"],
        button[class*="lookLink"] {
          background: transparent !important;
        }

        /* Discord's "selected/active" gray pills */
        [class*="selected"],
        [class*="active"] {
          --background-modifier-selected: var(--hyprmoni-wine-dark) !important;
        }

        /* ==================================================================
         * CHANNELS / SERVER LIST
         * ================================================================== */

        [class*="containerDefault"],
        [class*="wrapperDefault"],
        [class*="wrapperHovered"],
        [class*="wrapperSelected"] {
          border-radius: 0 !important;
        }

        [class*="modeSelected"] {
          background: var(--hyprmoni-wine-dark) !important;
          border-left: 2px solid var(--hyprmoni-pink) !important;
          border-radius: 0 !important;
        }

        [class*="modeSelected"] [class*="name"],
        [class*="modeSelected"] [class*="icon"] {
          color: var(--hyprmoni-blush) !important;
        }

        [class*="modeUnread"] [class*="name"] {
          color: var(--hyprmoni-peach) !important;
        }

        /* Server item hover/selection, without touching actual avatars */
        [class*="listItem"] [class*="wrapper"]:hover {
          background: var(--hyprmoni-wine-dark) !important;
          border-radius: 0 !important;
        }

        /* ==================================================================
         * MESSAGE AREA
         * ================================================================== */

        [class*="messageList"],
        [class*="scroller"],
        [class*="scrollableContainer"] {
          background-color: var(--hyprmoni-void) !important;
        }

        [class*="message"]:hover {
          background: color-mix(
            in srgb,
            var(--hyprmoni-panel) 88%,
            var(--hyprmoni-pink)
          ) !important;
        }

        [class*="message"] [class*="username"] {
          color: var(--hyprmoni-peach) !important;
        }

        [class*="timestamp"] {
          color: var(--hyprmoni-muted) !important;
        }

        [class*="channelTextArea"] {
          background: var(--hyprmoni-panel) !important;
          border: 1px solid var(--hyprmoni-wine) !important;
          border-radius: 0 !important;
          box-shadow: none !important;
        }

        [class*="channelTextArea"]:focus-within {
          border-color: var(--hyprmoni-pink) !important;
        }

        /* ==================================================================
         * CARDS / EMBEDS / PREVIEWS
         * ================================================================== */

        [class*="card"],
        [class*="cardPrimary"],
        [class*="cardSecondary"],
        [class*="embed"],
        [class*="embedFull"],
        [class*="embedWrapper"],
        [class*="embedInner"],
        [class*="attachment"],
        [class*="wrapper"][class*="embed"] {
          background: var(--hyprmoni-panel) !important;
          border-color: var(--hyprmoni-wine) !important;
          border-radius: 0 !important;
          box-shadow: none !important;
        }

        [class*="embed"] a {
          color: var(--hyprmoni-peach) !important;
        }

        [class*="embed"] [class*="title"] {
          background: transparent !important;
          border: 0 !important;
        }

        /* YouTube / link preview cards */
        [class*="embed"] [class*="embedDescription"],
        [class*="embed"] [class*="embedAuthor"],
        [class*="embed"] [class*="embedFooter"] {
          color: var(--hyprmoni-muted) !important;
        }

        /* ==================================================================
         * POPOUTS / MENUS / DIALOGS
         * ================================================================== */

        [role="menu"],
        [role="dialog"],
        [class*="popout"],
        [class*="layerContainer"] [class*="container"],
        [class*="menu"],
        [class*="contextMenu"] {
          background: var(--hyprmoni-panel) !important;
          border: 1px solid var(--hyprmoni-wine) !important;
          border-radius: 0 !important;
          box-shadow: 0 8px 24px rgba(0, 0, 0, 0.42) !important;
        }

        [role="menuitem"],
        [class*="menuItem"] {
          border-radius: 0 !important;
          color: var(--hyprmoni-blush) !important;
        }

        [role="menuitem"]:hover,
        [class*="menuItem"]:hover {
          background: var(--hyprmoni-wine-dark) !important;
          color: var(--hyprmoni-blush) !important;
        }

        /* ==================================================================
         * PROFILE / USER CARDS
         * ================================================================== */

        [class*="userPopout"],
        [class*="profilePopout"],
        [class*="profilePanel"],
        [class*="userProfileModal"] {
          background: var(--hyprmoni-panel) !important;
          border: 1px solid var(--hyprmoni-wine) !important;
          border-radius: 0 !important;
        }

        [class*="profile"] [class*="banner"] {
          border-radius: 0 !important;
        }

        /* Keep avatars circular */
        [class*="avatar"],
        img[class*="avatar"],
        [class*="avatarDecoration"] {
          border-radius: 50% !important;
        }

        /* ==================================================================
         * TOOLTIPS
         * ================================================================== */

        [class*="tooltip"],
        [role="tooltip"] {
          background: var(--hyprmoni-panel) !important;
          color: var(--hyprmoni-blush) !important;
          border: 1px solid var(--hyprmoni-wine) !important;
          border-radius: 0 !important;
          box-shadow: 0 6px 18px rgba(0, 0, 0, 0.45) !important;
        }

        /* ==================================================================
         * BADGES / CHIPS
         * ================================================================== */

        [class*="badge"],
        [class*="chip"],
        [class*="tag"],
        [class*="pill"] {
          border-radius: 0 !important;
        }

        /* ==================================================================
         * VENCORD
         * ================================================================== */

        [class*="vc-"],
        [class*="vc_"] {
          --brand-experiment: var(--hyprmoni-pink) !important;
          --text-brand: var(--hyprmoni-pink) !important;
          --text-link: var(--hyprmoni-peach) !important;
        }

        .vc-btn-base,
        .vc-btn-primary,
        .vc-btn-secondary {
          border-radius: 0 !important;
          box-shadow: none !important;
        }

        /* ==================================================================
         * LINKS / SELECTION / SCROLLBARS
         * ================================================================== */

        a {
          color: var(--hyprmoni-peach) !important;
        }

        a:hover {
          color: var(--hyprmoni-hot-pink) !important;
        }

        ::selection {
          background: var(--hyprmoni-pink) !important;
          color: var(--hyprmoni-void) !important;
        }

        ::-webkit-scrollbar {
          width: 8px !important;
          height: 8px !important;
        }

        ::-webkit-scrollbar-track {
          background: var(--hyprmoni-void) !important;
        }

        ::-webkit-scrollbar-thumb {
          background: var(--hyprmoni-wine) !important;
          border: 2px solid var(--hyprmoni-void) !important;
          border-radius: 0 !important;
        }

        ::-webkit-scrollbar-thumb:hover {
          background: var(--hyprmoni-pink) !important;
        }

        /* Remove surprise Discord shadows around otherwise flat UI */
        [class*="container"],
        [class*="card"],
        [class*="popout"],
        [class*="menu"] {
          box-shadow: none;
        }
      '';

      settings = {
        /* Vencord reads the generated theme declaratively. */
        useQuickCss = true;
        enabledThemes = [ "hyprmoni.theme.css" ];
      };
    };
  };
}
